'use strict'

const MOVIE_SEARCH_API_REQUEST = 'MOVIE_SEARCH_API_REQUEST';
const MOVIE_SEARCH_API_SUCCESS = 'MOVIE_SEARCH_API_SUCCESS';
const MOVIE_SEARCH_API_FAILURE = 'MOVIE_SEARCH_API_FAILURE';
const GET_LOCATIONDATA_MOVIE_REQUEST = 'GET_LOCATIONDATA_MOVIE_REQUEST';
const GET_LOCATIONDATA_MOVIE_SUCCESS = 'GET_LOCATIONDATA_MOVIE_SUCCESS';
const GET_LOCATIONDATA_MOVIE_FAILURE = 'GET_LOCATIONDATA_MOVIE_FAILURE';


export {
	MOVIE_SEARCH_API_REQUEST,
	MOVIE_SEARCH_API_SUCCESS,
	MOVIE_SEARCH_API_FAILURE,
	GET_LOCATIONDATA_MOVIE_REQUEST,
	GET_LOCATIONDATA_MOVIE_SUCCESS,
	GET_LOCATIONDATA_MOVIE_FAILURE
	
}