'use strict'

const LOAD_GOOGLE_API_REQUEST = 'LOAD_GOOGLE_API_REQUEST';
const LOAD_GOOGLE_API_SUCCESS = 'LOAD_GOOGLE_API_SUCCESS';
const LOAD_GOOGLE_API_FAILURE = 'LOAD_GOOGLE_API_FAILURE';
const GET_GEOCODE_REQUEST = 'GET_GEOCODE_REQUEST';
const GET_GEOCODE_SUCCESS = 'GET_GEOCODE_SUCCESS';
const GET_GEOCODE_FAILURE = 'GET_GEOCODE_FAILURE';

export {
	LOAD_GOOGLE_API_REQUEST,
	LOAD_GOOGLE_API_SUCCESS,
	LOAD_GOOGLE_API_FAILURE,
	GET_GEOCODE_REQUEST,
	GET_GEOCODE_SUCCESS,
	GET_GEOCODE_FAILURE

}